#!/usr/bin/ruby
# Copyright 2017 Randy Coburn
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This program is used to print out the last state file
# generated by the terraform runner. This will help
# make the statefile available outside of the container.

VERSION = '0.0.1'.freeze

TERRAFORM_DIR = '/terraform-runner/'.freeze

class TFStateFile
  def initialize(tf_dir)
    @tf_dir = tf_dir
  end

  # This function looks for the last working directory created
  # by the terraform-runner.rb program.
  def get_last_dir(root)
    Dir.glob("#{root}terraform-runner-working-dir*").sort[-1]
  end

  # This function returns the contents of the state file that
  # was collected by get_last_dir(). If there is no working
  # dir or if the statefile does not exist it will return an
  # empty json file. If it is there it will simply return it
  # so it can be printed out.
  def write_out_statefile
    output ='{}'
    unless get_last_dir(@tf_dir).nil?
      file_location=File.join(get_last_dir(@tf_dir),".terraform","terraform.tfstate")
      output = File.read(file_location) if File.exist?(file_location)
    end
    return output
  end
end
sf = TFStateFile.new(TERRAFORM_DIR)
puts sf.write_out_statefile
